package com.example.springboot.loader;

import com.example.springboot.constants.Roles;
import com.example.springboot.entities.Hospital;
import com.example.springboot.entities.Role;
import com.example.springboot.entities.User;
import com.example.springboot.repositories.HospitalRepository;
import com.example.springboot.repositories.RoleRepository;
import com.example.springboot.repositories.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import java.util.Arrays;
import java.util.List;

@Component
public class DatabaseLoader implements CommandLineRunner {
    private final RoleRepository roleRepository;
    private final UserRepository userRepository;
    private final HospitalRepository hospitalRepository;
    private final PasswordEncoder passwordEncoder;

    @Autowired
    public DatabaseLoader(RoleRepository roleRepository, UserRepository userRepository, HospitalRepository hospitalRepository, PasswordEncoder passwordEncoder) {
        this.roleRepository = roleRepository;
        this.userRepository = userRepository;
        this.hospitalRepository = hospitalRepository;
        this.passwordEncoder = passwordEncoder;
    }

    @Override
    public void run(String... args) throws Exception {
        if (this.roleRepository.count() == 0) {
            this.roleRepository.save(new Role(Roles.Admin));
            this.roleRepository.save(new Role(Roles.User));
            this.roleRepository.save(new Role(Roles.Doctor));
            this.roleRepository.save(new Role(Roles.Therapist));
            this.roleRepository.save(new Role(Roles.Surgeon));
        }
        if (this.hospitalRepository.count() == 0) {
            this.hospitalRepository.save(new Hospital("Rivne Central Hospital", "Rivne, Chornovola st., 26"));
            this.hospitalRepository.save(new Hospital("Lutsk Central Hospital", "Lutsk, Chornovola st., 6"));
            this.hospitalRepository.save(new Hospital("Lviv Central Hospital", "Lviv, Chornovola st., 2"));
            this.hospitalRepository.save(new Hospital("eu Hospital,", "6892 Natoque Ave"));
            this.hospitalRepository.save(new Hospital("Cras interdum. Nunc", "P.O. Box 450, 7716 Dolor Av."));
            this.hospitalRepository.save(new Hospital("libero. Proin sed", "P.O. Box 182, 4315 Nunc Road"));
            this.hospitalRepository.save(new Hospital("non sapien", "Ap #405-1326 Cum St."));
            this.hospitalRepository.save(new Hospital("sem ut", "549-6025 Mus. Av."));
            this.hospitalRepository.save(new Hospital("a,", "Ap #728-5706 Sem. Rd."));
            this.hospitalRepository.save(new Hospital("eu Hospital Center", "Ap #412-6882 Pellentesque St."));
            this.hospitalRepository.save(new Hospital("nisi dictum", "885-8522 Nisi. Rd."));
            this.hospitalRepository.save(new Hospital("elit.", "191-9767 Egestas St."));
            this.hospitalRepository.save(new Hospital("ipsum non arcu a.", "8538 Dolor Av."));
            this.hospitalRepository.save(new Hospital("elit. Curabitur", "9235 Metus. Rd."));
            this.hospitalRepository.save(new Hospital("libero lacus, varius", "2589 Lacus. St."));
            this.hospitalRepository.save(new Hospital("commodo auctor velit.", "3484 Risus, St."));
            this.hospitalRepository.save(new Hospital("cursus in,", "858-4272 Pharetra Avenue"));
            this.hospitalRepository.save(new Hospital("tellus sem mollis", "P.O. Box 110, 1163 Nam Rd."));
            this.hospitalRepository.save(new Hospital("Aenean sed pede", "P.O. Box 631, 7822 Et Rd."));
            this.hospitalRepository.save(new Hospital("sem egestas", "P.O. Box 686, 4543 Risus. Avenue"));
            this.hospitalRepository.save(new Hospital("orci tincidunt", "1290 Nisl. Rd."));
            this.hospitalRepository.save(new Hospital("Cras dolor dolor,", "Ap #804-6614 Sit St."));
            this.hospitalRepository.save(new Hospital("aliquam", "P.O. Box 836, 5937 Donec Rd."));
            this.hospitalRepository.save(new Hospital("eu nibh", "612-8324 Egestas Ave"));
            this.hospitalRepository.save(new Hospital("lorem, vehicula et,", "601-8294 Penatibus Ave"));
            this.hospitalRepository.save(new Hospital("lobortis", "Ap #404-9543 Vel, Street"));
            this.hospitalRepository.save(new Hospital("Cras", "Ap #164-3736 Orci Street"));
            this.hospitalRepository.save(new Hospital("tristique neque", "P.O. Box 743, 7456 Nisi Ave"));
            this.hospitalRepository.save(new Hospital("ornare egestas ligula.", "672-9373 Quis, Av."));
            this.hospitalRepository.save(new Hospital("id, erat. Etiam", "P.O. Box 164, 1301 Id, Avenue"));
            this.hospitalRepository.save(new Hospital("laoreet, libero", "695-8038 Nunc Rd."));
            this.hospitalRepository.save(new Hospital("Nam tempor diam", "2703 Dictum Rd."));
            this.hospitalRepository.save(new Hospital("Suspendisse dui. Fusce", "1676 Consectetuer St."));
            this.hospitalRepository.save(new Hospital("risus. Nunc ac", "272-7696 Mi. Rd."));
            this.hospitalRepository.save(new Hospital("est. Nunc", "P.O. Box 739, 2111 Venenatis Road"));
            this.hospitalRepository.save(new Hospital("ultricies dignissim lacus.", "986-3112 Sollicitudin Rd."));
            this.hospitalRepository.save(new Hospital("fringilla euismod", "9788 Pulvinar Rd."));
            this.hospitalRepository.save(new Hospital("Proin", "P.O. Box 914, 8924 Dignissim Road"));
            this.hospitalRepository.save(new Hospital("consequat", "8570 Tristique Av."));
            this.hospitalRepository.save(new Hospital("nibh. Phasellus", "161-5193 Lorem St."));
            this.hospitalRepository.save(new Hospital("Lorem", "650-1735 Magna St."));
            this.hospitalRepository.save(new Hospital("arcu. Morbi sit", "101-2868 Nullam Road"));
            this.hospitalRepository.save(new Hospital("arcu", "Ap #481-5025 Sapien, St."));
            this.hospitalRepository.save(new Hospital("condimentum", "767-5508 Et Rd."));
            this.hospitalRepository.save(new Hospital("leo. Morbi neque", "P.O. Box 803, 7524 Dignissim St."));
            this.hospitalRepository.save(new Hospital("odio vel est", "Ap #680-5263 A, Road"));
            this.hospitalRepository.save(new Hospital("consectetuer", "7437 Odio. Av."));
            this.hospitalRepository.save(new Hospital("id nunc interdum", "P.O. Box 363, 2965 Hymenaeos. Av."));
            this.hospitalRepository.save(new Hospital("dis parturient", "P.O. Box 987, 3973 Risus. Av."));
            this.hospitalRepository.save(new Hospital("neque.", "8429 In Ave"));
            this.hospitalRepository.save(new Hospital("mauris blandit", "P.O. Box 744, 8256 Torquent Avenue"));
            this.hospitalRepository.save(new Hospital("mattis. Cras", "623-973 Donec St."));
            this.hospitalRepository.save(new Hospital("amet massa. Quisque", "P.O. Box 146, 3154 Lobortis Street"));
            this.hospitalRepository.save(new Hospital("aliquet vel, vulputate", "Ap #581-5241 Dictum Rd."));
            this.hospitalRepository.save(new Hospital("nec tempus", "P.O. Box 533, 8010 A, Av."));
            this.hospitalRepository.save(new Hospital("tortor nibh sit", "651-8092 Dapibus Avenue"));
            this.hospitalRepository.save(new Hospital("in sodales", "588-991 Velit St."));
            this.hospitalRepository.save(new Hospital("fermentum metus.", "7558 Consectetuer Avenue"));
            this.hospitalRepository.save(new Hospital("fringilla purus", "P.O. Box 891, 6356 Aliquam Rd."));
            this.hospitalRepository.save(new Hospital("Suspendisse commodo tincidunt", "277-9866 Sed Avenue"));
            this.hospitalRepository.save(new Hospital("feugiat.", "835-5757 Sagittis Street"));
            this.hospitalRepository.save(new Hospital("erat", "Ap #833-2394 Adipiscing Rd."));
            this.hospitalRepository.save(new Hospital("at, velit. Pellentesque", "857-4601 Sed St."));
            this.hospitalRepository.save(new Hospital("Mauris", "7037 Ut Street"));
            this.hospitalRepository.save(new Hospital("Cras vehicula aliquet", "413-3671 Vehicula. Avenue"));
            this.hospitalRepository.save(new Hospital("magna. Phasellus dolor", "Ap #210-5540 Vehicula Road"));
            this.hospitalRepository.save(new Hospital("interdum ligula eu", "Ap #580-5574 Feugiat St."));
            this.hospitalRepository.save(new Hospital("Donec est.", "P.O. Box 244, 5425 Nibh Street"));
            this.hospitalRepository.save(new Hospital("Etiam gravida", "1241 Id Road"));
            this.hospitalRepository.save(new Hospital("fermentum fermentum", "Ap #696-148 Sem Street"));
            this.hospitalRepository.save(new Hospital("magna. Phasellus", "Ap #657-5933 Fermentum St."));
            this.hospitalRepository.save(new Hospital("auctor vitae, aliquet", "Ap #285-3774 Donec Road"));
            this.hospitalRepository.save(new Hospital("sed", "P.O. Box 367, 7508 Mi. Avenue"));
            this.hospitalRepository.save(new Hospital("per inceptos", "2774 Dapibus Street"));
            this.hospitalRepository.save(new Hospital("sapien,", "882-2158 Nullam Rd."));
            this.hospitalRepository.save(new Hospital("vitae", "4695 Elit. Avenue"));
            this.hospitalRepository.save(new Hospital("mi", "8444 Phasellus Ave"));
            this.hospitalRepository.save(new Hospital("at,", "2297 Velit Road"));
            this.hospitalRepository.save(new Hospital("litora torquent", "P.O. Box 562, 5761 Nec St."));
            this.hospitalRepository.save(new Hospital("odio. Phasellus", "P.O. Box 234, 4028 Nullam Street"));
            this.hospitalRepository.save(new Hospital("nibh", "288-8048 Ut Road"));
            this.hospitalRepository.save(new Hospital("malesuada fames ac", "7859 Purus Rd."));
            this.hospitalRepository.save(new Hospital("eu", "6709 Ut Street"));
            this.hospitalRepository.save(new Hospital("et, euismod", "Ap #120-2110 Massa. Avenue"));
            this.hospitalRepository.save(new Hospital("Proin eget", "Ap #377-4774 Non Rd."));
            this.hospitalRepository.save(new Hospital("enim", "405-128 Integer Street"));
            this.hospitalRepository.save(new Hospital("mollis nec,", "1317 Proin Rd."));
            this.hospitalRepository.save(new Hospital("sagittis", "994-8764 Amet, Avenue"));
            this.hospitalRepository.save(new Hospital("parturient montes,", "7618 Mi Rd."));
            this.hospitalRepository.save(new Hospital("gravida nunc", "Ap #939-547 Eget, Street"));
            this.hospitalRepository.save(new Hospital("non,", "P.O. Box 641, 6577 Duis Road"));
            this.hospitalRepository.save(new Hospital("ipsum non arcu hj", "Ap #944-9005 Lobortis, Street"));
            this.hospitalRepository.save(new Hospital("libero", "Ap #806-4752 Elit, St."));
            this.hospitalRepository.save(new Hospital("ut mi.", "Ap #989-7243 Ac Rd."));
            this.hospitalRepository.save(new Hospital("ornare.", "692-6549 Sed, St."));
            this.hospitalRepository.save(new Hospital("aliquet", "214-8678 Diam Road"));
            this.hospitalRepository.save(new Hospital("Nullam lobortis", "379 Egestas Street"));
            this.hospitalRepository.save(new Hospital("Mauris ut quam", "P.O. Box 685, 9204 Vivamus Rd."));
            this.hospitalRepository.save(new Hospital("eget nisi", "Ap #522-8430 Fusce Road"));
            this.hospitalRepository.save(new Hospital("pede, nonummy", "1518 Elit Street"));
            this.hospitalRepository.save(new Hospital("vehicula", "6580 Tellus Ave"));
            this.hospitalRepository.save(new Hospital("natoque penatibus", "Ap #647-9486 Ut St."));
            this.hospitalRepository.save(new Hospital("Fusce aliquam, enim", "584-5041 A Rd."));
        }
        if (this.userRepository.count() == 0) {
            this.userRepository.save(new User("semen@gmail.com", passwordEncoder.encode("123456"), Arrays.asList(roleRepository.findByName(Roles.User))));
            this.userRepository.save(new User("admin@gmail.com", passwordEncoder.encode("123456"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Admin))));
            this.userRepository.save(new User("Oleh", "Kravchuk", "therapist@gmail.com", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Oleksiy", "Tkachuk", "surgeon@gmail.com", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lutsk Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Surgeon))));
            this.userRepository.save(new User("Felicia", "Donovan", "arcu.Curabitur.ut@penatibuset.net", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Thomas", "Mullen", "magna.Ut.tincidunt@faucibus.com", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Kevyn", "Whitaker", "Donec.sollicitudin.adipiscing@risus.org", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Maxine", "Howell", "neque.vitae@pellentesqueafacilisis.co.uk", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Amela", "Morrow", "vel.turpis.Aliquam@purus.co.uk", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lutsk Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Kyla", "Rios", "Phasellus.ornare@placeratCras.com", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lutsk Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Inga", "Lloyd", "Ut.nec@dolor.net", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lutsk Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Angelica", "Smith", "tempus.mauris@semperdui.ca", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Rashad", "Gomez", "Nullam.enim.Sed@Nunc.co.uk", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Nina", "Larsen", "ac@natoquepenatibuset.org", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lutsk Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Adria", "Juarez", "nisi.magna@et.net", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Sophia", "Bender", "neque.sed.sem@magnaDuisdignissim.net", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Clark", "Clark", "purus@indolor.ca", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lutsk Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Katell", "Whitfield", "a.facilisis.non@Intincidunt.net", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Kelsie", "Madden", "libero.Integer@ante.co.uk", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lutsk Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Molly", "Frank", "risus@Donecnibh.net", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Amaya", "Gardner", "diam@dolor.com", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Lyle", "Gregory", "et.nunc.Quisque@nibhsitamet.net", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Sylvester", "Preston", "sollicitudin.orci@Nullam.org", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lutsk Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Jarrod", "Kirby", "enim.Curabitur.massa@inceptos.ca", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Gavin", "Gross", "Nulla.tempor@acmattisvelit.com", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lutsk Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Hashim", "Wright", "sagittis.placerat@Nulla.net", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lutsk Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Minerva", "Bass", "id@luctus.edu", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lutsk Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Sierra", "Rocha", "Cras@maurisipsumporta.ca", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lutsk Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Ahmed", "Davidson", "Duis.sit.amet@cursusinhendrerit.edu", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Lionel", "Mayer", "Cras@eleifendvitaeerat.ca", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lutsk Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Phyllis", "Blanchard", "eget@lacus.org", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lutsk Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Angelica", "Nieves", "amet@DonecfringillaDonec.net", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Eaton", "Marquez", "nibh.Aliquam@Aliquam.co.uk", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lutsk Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Kenneth", "Higgins", "Donec.consectetuer.mauris@sapienNunc.org", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Jared", "Fleming", "egestas.urna@egestas.net", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lutsk Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Lani", "Good", "vel@malesuada.edu", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lviv Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Illiana", "Ashley", "felis@arcu.edu", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lviv Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Arsenio", "Coffey", "Proin.velit@facilisisfacilisismagna.edu", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Kelsie", "Solis", "risus@nequesedsem.ca", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lviv Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Craig", "Garrison", "eu@malesuadafamesac.org", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lviv Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Ocean", "Tran", "Duis.gravida@nuncsed.com", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Veronica", "Rosa", "magna@erosturpis.com", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Ulla", "Dawson", "fringilla@velitegestas.co.uk", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Naomi", "Paul", "sodales.purus.in@Cumsociisnatoque.co.uk", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Yolanda", "Rowe", "Phasellus@habitantmorbitristique.co.uk", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lviv Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Hilel", "Howe", "facilisi@nonenimcommodo.co.uk", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lviv Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Illana", "Bush", "sem.egestas@tinciduntcongue.net", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lviv Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Fulton", "Eaton", "eu.placerat.eget@estarcu.co.uk", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Elaine", "Barrera", "lorem.fringilla@Nullam.ca", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Elliott", "Colon", "ut.lacus@nonummyFuscefermentum.net", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Dominic", "Melton", "nec.ante@Loremipsumdolor.edu", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Wayne", "Love", "et@Aliquamrutrumlorem.co.uk", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Seth", "Guerra", "gravida.molestie@arcueuodio.ca", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Julian", "Meadows", "scelerisque.dui.Suspendisse@erat.com", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Xyla", "Gilliam", "fringilla.est.Mauris@neccursusa.com", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Ivan", "Black", "fermentum.vel@necquam.org", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lviv Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Tanya", "Yang", "Duis.mi@ultriciesornare.edu", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lviv Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Colby", "Yates", "sem.elit@rutrumeu.org", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lviv Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Oren", "Wood", "mauris@Morbisit.com", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lviv Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Martin", "Gonzales", "aliquet.lobortis.nisi@pellentesque.org", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Deanna", "Humphrey", "lobortis.augue.scelerisque@Aliquam.com", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Hashim", "Cochran", "id.mollis.nec@netusetmalesuada.edu", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Uriah", "Rivera", "Aliquam.gravida@fringillaornare.org", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Stella", "Kemp", "felis.Donec@nibh.com", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lviv Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Mechelle", "Morse", "ornare.tortor.at@nibhvulputate.net", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Surgeon))));
            this.userRepository.save(new User("Kiona", "Odonnell", "dignissim.Maecenas@fringilla.org", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Benedict", "Mullins", "egestas@nuncInat.edu", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lviv Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Chava", "England", "porttitor.interdum.Sed@quam.com", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Surgeon))));
            this.userRepository.save(new User("Hayley", "Marshall", "turpis@egestas.ca", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lviv Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Odysseus", "Rowland", "nunc.sit@lobortisClassaptent.org", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Holmes", "Woods", "et.tristique.pellentesque@seddictum.net", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Isaiah", "Gates", "et.arcu@nisidictumaugue.co.uk", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Coby", "Frye", "nec.urna.et@In.net", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Brandon", "Harrison", "eget.volutpat.ornare@Proinvelit.org", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Maia", "Benjamin", "rhoncus.Donec.est@Suspendisseeleifend.org", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Carlos", "Cooper", "Pellentesque.tincidunt@amet.ca", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Surgeon))));
            this.userRepository.save(new User("Marah", "Parks", "eu@velarcuCurabitur.ca", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lviv Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Merrill", "Mendez", "neque.Nullam@mollis.org", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Channing", "Suarez", "pharetra.ut.pharetra@est.com", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Surgeon))));
            this.userRepository.save(new User("Abigail", "Prince", "ultrices.iaculis@magnaDuis.edu", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Cally", "Sosa", "Praesent.eu.dui@necenim.edu", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Tasha", "Stokes", "imperdiet@nuncnullavulputate.org", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Surgeon))));
            this.userRepository.save(new User("Dale", "Sosa", "ante@natoque.ca", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Fuller", "Hernandez", "Cras@liberoet.org", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Rae", "King", "eget.nisi@rutrumurna.co.uk", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lviv Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Gail", "Ferguson", "dapibus.id@vitaepurus.org", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Sydney", "Carson", "ante@augueeutempor.org", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Surgeon))));
            this.userRepository.save(new User("Troy", "Dodson", "diam.dictum@ipsumCurabitur.com", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Noelle", "Barron", "aliquet.Proin@Aliquamfringilla.co.uk", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Dahlia", "Marshall", "Quisque.varius.Nam@Quisqueac.ca", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Surgeon))));
            this.userRepository.save(new User("David", "Best", "tellus@eros.ca", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Fletcher", "Sims", "semper@aliquet.edu", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Marvin", "Mccoy", "eu.erat@orci.net", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Rigel", "Burris", "sociosqu.ad.litora@pulvinararcuet.net", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Rhona", "Wilkerson", "augue.eu.tempor@fermentum.co.uk", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Surgeon))));
            this.userRepository.save(new User("Helen", "Valentine", "inceptos.hymenaeos@aarcuSed.ca", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Amelia", "Whitley", "Duis@sitametlorem.net", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Igor", "Mays", "ante@Nullamut.com", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Salvador", "Burke", "sed.orci.lobortis@lacinia.ca", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Gabriel", "Livingston", "gravida.molestie.arcu@Phasellus.net", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Zephania", "Abbott", "Sed@nislMaecenasmalesuada.edu", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Maya", "Tyler", "Phasellus.in.felis@eusemPellentesque.ca", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Jane", "Beck", "semper@leo.edu", passwordEncoder.encode("123456"), hospitalRepository.findByName("Rivne Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
            this.userRepository.save(new User("Gemma", "Mckinney", "euismod.est.arcu@senectuset.com", passwordEncoder.encode("123456"), hospitalRepository.findByName("Lutsk Central Hospital"), Arrays.asList(roleRepository.findByName(Roles.User), roleRepository.findByName(Roles.Doctor), roleRepository.findByName(Roles.Therapist))));
        }
    }
}
